### ISSUE TITLE
Deform an already deformed block.

### ISSUE THREAD

**Issue by mberry28** [danigeos/tisc#2]
Suppose that I extend a fault block away from the interior the model domain, after a period of motion, a new .UNIT file is invoked which defines a new block that is in the "interior" of the first block (see attached cross section for example, yellow box moves west first, followed by the red interior). TISC, as I understand it, is not able to do this. Are there any work arounds for this?  

![rgcs_an](https://cloud.githubusercontent.com/assets/13278376/13608290/582c94ea-e511-11e5-962c-dcd2c9c4f167.png)

**Comment by danigeos** [comment]
Nice section.
Yes, TISC can do this. You need to look at the parameters in tisc/doc/template.UNIT file: 
Define first the yellow one (eg., project1.UNIT) then the red (project2.UNIT) 
time_stop will allow you to stop the yellow unit when you wish.
cut_all will allow the red unit to cut the yellow one.

**Comment by danigeos** [comment]
can you try edit this FAQ?

https://github.com/danigeos/tisc/wiki/FAQ

**Comment by mberry28** [comment]
I will try this in a bit. Thanks.

Yes, It does look like I can edit the Wiki pages. Would you prefer me to use that instead?

I hope that you know I do spend a while in the docs and demos before I ask a question. I sometimes feel like these are dumb questions ;)

**Comment by danigeos** [comment]
nevermind, it's normal. I have repeated this process a few times already.
The important thing is that at least our discussion can help others in the
future, that's the purpose of the wiki thing. If it is a well-structured
question it can have it's own wiki page, or add it to the FAQ if it is a
frequent one,
I already uploaded the tisc.info.txt, for example, you can edit the file
yourself or add a new one.
Uploading the templates as wiki pages would be fine, for example. Then you
can extend the commentaries at your will.
The purpose is to let the wiki be the real TISC guide in the future.
It's a good place for exchange, but i'm new to it too.

**Comment by mberry28** [comment]
Great. I've made a hand full of personal tisc notes. I will add them to the
page. I did add a question to the FAQ. Feel free to edit what I add.
