### ISSUE TITLE
Initial conditions

### ISSUE THREAD

**Issue by hanhydro** [danigeos/tisc#23]
Dear Dr. Garcia-Castellanos,

I was wondering if you could direct me to the lines of TISC code where it deals with initial conditions of both isostasy (fourth-order) and landscape diffusion (second-order) equations to pass them to the solver.

I figured out the boundary conditions and have to know how TISC assigns initial conditions for the equations above.

Thank you.

Doe Han
New Mexico Tech

**Comment by danigeos** [comment]
Hi,
4 sets of boundary conditions can be specified via the PRM input file.

I don't understand what do you mean by initial conditions.

**Comment by mberry28** [comment]
Doe,

I am also not sure what you mean by initial conditions, for flexure, do you mean effective elastic thickness and viscous relaxation? Those are located in tisc.c, look for the functions below.

	Elastic_Deflection();

Landscape diffusion is just a coefficent and the code is in surf_proc(), look for:
Diffusive_Eros 

	Viscous_Relaxation();

**Comment by hanhydro** [comment]
Hi all,

Great. I got everything I needed. 

Thank you for your help!


Doe
