### ISSUE TITLE
Virtual machine file with password restriction

### ISSUE THREAD

**Issue by mehmetdokuz** [danigeos/tisc#26]

**Comment by danigeos** [comment]
Hi, did you solve the issue?

**Comment by mehmetdokuz** [comment]
Thank you, but I could not solve it. When I call the file with VM, it seems
working but but requires password.

Δρ(Garcia-Castellanos) ***@***.***>, 30 Kas 2023 Per, 13:11
tarihinde şunu yazdı:

> Hi, did you solve the issue?
>

**Comment by danigeos** [comment]
Try this:

Maquina virtual Ubuntu 20.04 -- GMT 4.5.18
Usuario: usuario
Passwd: usuario20
GMT 4.5.18
/home/usuario/Software/gmt-4.5.18

**Comment by mehmetdokuz** [comment]
Thank you, it worked perfectly.

Δρ(Garcia-Castellanos) ***@***.***>, 1 Ara 2023 Cum, 19:06
tarihinde şunu yazdı:

> Try this:
>
> Maquina virtual Ubuntu 20.04 -- GMT 4.5.18
> Usuario: usuario
> Passwd: usuario20
> GMT 4.5.18
> /home/usuario/Software/gmt-4.5.18
>
>
>
