### ISSUE TITLE
Vertical Uplift

### ISSUE THREAD

**Issue by mberry28** [danigeos/tisc#3]
I understand there is a way to create hidden loads, which creates subsidence. But is there a way to create uplift without any lateral thrusting? For example, similar to the Colorado Plateau?

**Comment by danigeos** [comment]
hidden loads (using the header line 'hidden 1' in the *.UNIT input file) accept both positive and negative thickness as z-values. TISC then multiplies that thickness by the density specified in the header to obtain the pressure applied at every cell [Pa]. A negative density OR thickness will imply a buoyant (upwards) force.
