### ISSUE TITLE
Erodibility values

### ISSUE THREAD

**Issue by mberry28** [danigeos/tisc#5]
Hi Daniel,

Needed some clarification on some methods used

When discussing the erodibility values (e.g. G-C and Villasenor 2011, using model 6) you reference a few sources to compare the values you use with (e.g. Lave and Avouac 2001). Reading those papers they use a value like 0.107 m/yr, whereas you use 2e-4 m/yr /Pa. It seems that you solve for the shear force applied to the rock by the river to get a erodibility per unit force (to get the 'per Pascal'), compared to the papers cited just solve the erodibility of the particular river-bedrock system. Is this correct? The three papers I have read so far, it doesn't seem that they do any normalizing.

I am focusing on TISC's 'erosed_model 6', and I did notice that the recommended erodibility values vary by orders of magnitude between models. 

Thanks

**Comment by danigeos** [comment]
@mberry28, 
the erodabilities cited for L&A2001 come from the slope of the data in their fig. 8b (units: mm yr^-1 Pa^-1). This is erosion rate divided shear stress, thus perfectly corresponding to erosed_model 6 (adopting a=1, see Garcia-Castellanos & Jimenez-Munt, 2015). In TISC a=1.5 is used by default, and you need to edit the code if you want to use a=1. So my recommendation for the moment is that you use a=1.5, adopting values cited in this 2015 paper. 

But remember the bottom line: those erodability values are just a reference. Many factors like lithology, vegetation, etc can have an effect on them. So you'll need to move them up or down by >1 order of magnitude to fit the sedimentary budget and average climate of your basin.

**Comment by mberry28** [comment]
That makes a lot of sense, thanks.
