### ISSUE TITLE
Adjusting parameters for specific nodes / changing the initial geometry and properties distribution

### ISSUE THREAD

**Issue by mberry28** [danigeos/tisc#7]
In a proj.PRM file, we are able to assign various parameters for the whole model domain. Suppose we want a region that has a different parameter (e.g. erodibility), without applying a load or package on top of the "bedrock" topography. For example, if we want a thrust sheet of higher density and less erodiblity, we want half the domain to have easily erodible material.

I tried to apply that parameter to a proj.UNIT. It did not work, unless I created it something like a load (similar to tisc/demo/3_flex). 

proj.NDEF seemed to be mainly for adding water or sediment.

Are there any methods for doing this?

Thanks

**Comment by danigeos** [comment]
Do you mean changing the initial geometry/properties distribution?
The trick is to use a *.UNIT file with the 'cut_all 1' and a different erodability specified at the header. 
It will cut your bedrock, create a unit, and change its properties.

**Comment by mberry28** [comment]
I have been working with this and I haven't gotten it to work yet. Here is what I am doing in the .UNIT files, I am using an .ZINI to define an initial slope to the model:

(I've tried with inputing time and time_stop and without)
erodibility 1e-8
cut_all 1
cut_unit 1 (tired with and without this)
mode_interp 4
00
x1 value y1 value
x2 value y2 value
x3 value y3 value
x4 value y4 value
...
(I have also tried to move the z contour value around, even more more than one contour. 

I have also tried different interpolation modes, for example
using: 
mode_interp 0
x y z 
z y z
x y z
(where x y z is node values and elevation)

**Comment by danigeos** [comment]
you are missing the "fault 1", without this i wont read the cut_all, i believe. 
The trick is to use a fault with zero velocity. It cuts and it changes the properties according to the headers.
