### ISSUE TITLE
Changing velocites of a fault block with .UNIT files

### ISSUE THREAD

**Issue by mberry28** [danigeos/tisc#8]
I'm sure that you are tired of me!

I've been stuck on this one for a few days...
If I have one fault block, and I want to change the velocity of a fault block, I basically copy proj1.UNIT to proj2.UNIT and change the velocity value and redefine the time and time_stop values, and everything works fine. I have done this numerous times.

However...

Suppose that I have 2 separate fault blocks defined proj1.UNIT and proj2.UNIT. If I want to change the velocity of each of those blocks, and copy proj1.UNIT and proj2.UNIT to proj3.UNIT and proj4.UNIT respectively, change the velocity and the time values and it should work (making sure that the numbers in the .UNIT in order of timing). However, it doesn't seem to read the proj3.UNIT or proj4.UNIT files.  I have troubleshooted this by rearranging the file name numbers with no success. 

Any pointers?

**Comment by danigeos** [comment]
Your strategy seems correct, so you should send me the input files so that i can try them. 
Meanwhile, check out the cut_all, cut_units, etc available parameters at the template.UNIT

**Comment by mberry28** [comment]
See attached.

I have been toying with the order of the .UNIT files so if they seem out of order that will be why.

Thanks




[RGR.zip](https://github.com/danigeos/tisc/files/299389/RGR.zip)

**Comment by danigeos** [comment]
The time_final in the PRM is < than the time in the last two units, so it did not reach to read them.
But anyway, you just have to add the 'cut_all 1', as i said, then it changes de velocity displayed at the en of the tisc run, on the screen.

You setup seems to gradually improve!

**Comment by danigeos** [comment]
@mberry28 can you close the issue if this was already clarified?
